package com.example.springmvc.exception;

public enum ErrorCode {

    VALIDATION_ERROR,
     INVALID_REQUEST,
    INTERNAL_SERVER_ERROR,

    VENDOR_NOT_FOUND,
    CATEGORY_NOT_FOUND,

    UNAUTHORIZED,
    FORBIDDEN,
    INVALID_CREDENTIALS,

    USER_NOT_FOUND,

    PRODUCT_NOT_FOUND,
    PRODUCT_VARIANT_NOT_FOUND,
    DUPLICATE_PRODUCT_VARIANT,
    PRODUCT_OUT_OF_STOCK,

    ORDER_NOT_FOUND,
    ORDER_STATE_ERROR,
}
